#!/bin/bash
# System Information
hostname=$(hostname)
os=$(source /etc/os-release && echo "$PRETTY_NAME")
uptime=$(uptime -p)
# Hardware Information
cpu=$(grep "model name" /proc/cpuinfo | head -n1 | cut -d: -f2 | sed 's/^[[:space:]]*//')
cpu_speed=$(grep "cpu MHz" /proc/cpuinfo | head -n1 | cut -d: -f2 | sed 's/^[[:space:]]*//')
cpu_max_speed=$(grep "cpu MHz" /proc/cpuinfo | tail -n1 | cut -d: -f2 | sed 's/^[[:space:]]*//')
ram=$(free -h | awk '/Mem/ {print $2}')
disks=$(lsblk -o NAME,SIZE,MODEL | awk '$1!="NAME" {print $2, $3}')
video=$(lspci | grep "VGA compatible controller" | awk -F': ' '{print $3}')
# Network Information
fqdn=$(hostname -f)
host_address=$(ip addr show eth0 | awk '/inet / {print $2}')
gateway_ip=$(ip route | awk '/default via/ {print $3}')
dns_server=$(cat /etc/resolv.conf | awk '/nameserver/ {print $2}')
interface_name=$(ip addr show eth0 | awk '/inet / {print $NF}')
#ip_address=$(ip addr show | awk '/inet .* brd/ {print $2}')
ip_address=$(ip -o -4 addr show | awk '!/^[0-9]*: ?lo|link\/ether/ {print $4; exit}')
# System Status
users=$(who | awk '{print $1}' | sort -u)
disk_space=$(df -h | awk '$NF ~ /^\// {print $1, $4}')
process_count=$(ps aux --no-headers | wc -l)
load_averages=$(uptime | awk -F'[a-z]:' '{print $2}')
memory_allocation=$(free -h | awk '/Mem/ {print $3 "/" $2}')
listening_ports=$(ss -tln | awk 'NR>1 {print $4}' | awk -F':' '{print $NF}' | sort -u)
ufw_rules=$(sudo ufw status verbose | awk '/^Rules:/ {flag=1; next} flag')
# Generating the report
cat <<EOF

System Report generated by $(whoami), $(date +"%Y-%m-%d %H:%M:%S")

System Information
-------------------
Hostname: $hostname
OS: $os
Uptime: $uptime

Hardware Information
----------------------
CPU: $cpu
Speed: $cpu_speed (current), $cpu_max_speed (max)
RAM: $ram
Disk(s): $disks
Video: $video

Network Information
---------------------
FQDN: $fqdn
Host Address: $host_address
Gateway IP: $gateway_ip
DNS Server: $dns_server

Interface Name: $interface_name
IP Address: $ip_address

System Status
--------------
Users Logged In: $users
Disk Space: $disk_space
Process Count: $process_count
Load Averages: $load_averages
Memory Allocation: $memory_allocation
Listening Network Ports: $listening_ports
UFW Rules: $ufw_rules

EOF
